REFRESH MATERIALIZED VIEW celsius_daily_average;
REFRESH MATERIALIZED VIEW celsius_weekly_average;
REFRESH MATERIALIZED VIEW celsius_monthly_average;
REFRESH MATERIALIZED VIEW humidity_daily_average;
REFRESH MATERIALIZED VIEW humidity_monthly_average;
